import { buildCsvFromRecords } from "@/lib/csv";

export const SAMPLE_HEADERS = [
  "Sales record number",
  "Order number",
  "Buyer username",
  "Post to name",
  "Post to phone",
  "Post to address 1",
  "Post to address 2",
  "Post to city",
  "Post to county",
  "Post to postcode",
  "Post to country",
  "Item title",
  "Quantity",
] as const;

type SampleRow = Record<(typeof SAMPLE_HEADERS)[number], string>;

function row(values: SampleRow): SampleRow {
  return values;
}

const SAMPLE_ROWS: SampleRow[] = [
  row({
    "Sales record number": "1001",
    "Order number": "ORD-1001",
    "Buyer username": "alice_uk",
    "Post to name": "Alice Hart",
    "Post to phone": "07700 900111",
    "Post to address 1": "12 Maple Street",
    "Post to address 2": "",
    "Post to city": "York",
    "Post to county": "North Yorkshire",
    "Post to postcode": "YO1 7HH",
    "Post to country": "United Kingdom",
    "Item title": "Ceramic mug",
    Quantity: "1",
  }),
  row({
    "Sales record number": "1002",
    "Order number": "ORD-1002",
    "Buyer username": "bob_shopper",
    "Post to name": "Bob Keene",
    "Post to phone": "0161 496 0100",
    "Post to address 1": "44 Canal Walk",
    "Post to address 2": "Apartment 3",
    "Post to city": "Manchester",
    "Post to county": "Greater Manchester",
    "Post to postcode": "M1 1AE",
    "Post to country": "United Kingdom",
    "Item title": "Blue notebook",
    Quantity: "1",
  }),
  row({
    "Sales record number": "1002",
    "Order number": "ORD-1002",
    "Buyer username": "bob_shopper",
    "Post to name": "Bob Keene",
    "Post to phone": "0161 496 0100",
    "Post to address 1": "44 Canal Walk",
    "Post to address 2": "Apartment 3",
    "Post to city": "Manchester",
    "Post to county": "Greater Manchester",
    "Post to postcode": "M1 1AE",
    "Post to country": "United Kingdom",
    "Item title": "Gel pen set",
    Quantity: "2",
  }),
  row({
    "Sales record number": "1002",
    "Order number": "ORD-1002",
    "Buyer username": "bob_shopper",
    "Post to name": "Bob Keene",
    "Post to phone": "0161 496 0100",
    "Post to address 1": "44 Canal Walk",
    "Post to address 2": "Apartment 3",
    "Post to city": "Manchester",
    "Post to county": "Greater Manchester",
    "Post to postcode": "M1 1AE",
    "Post to country": "United Kingdom",
    "Item title": "Desk blotter",
    Quantity: "1",
  }),
  row({
    "Sales record number": "2001",
    "Order number": "ORD-2001",
    "Buyer username": "priya_shah",
    "Post to name": "Priya Shah",
    "Post to phone": "020 7946 0958",
    "Post to address 1": "8 Crown Court",
    "Post to address 2": "W/N",
    "Post to city": "London",
    "Post to county": "Greater London",
    "Post to postcode": "WC2N 5DU",
    "Post to country": "United Kingdom",
    "Item title": "Print: river morning",
    Quantity: "1",
  }),
  row({
    "Sales record number": "2002",
    "Order number": "ORD-2002",
    "Buyer username": "priya_shah",
    "Post to name": "Priya Shah",
    "Post to phone": "020 7946 0958",
    "Post to address 1": "8 Crown Court",
    "Post to address 2": "W/N",
    "Post to city": "London",
    "Post to county": "Greater London",
    "Post to postcode": "WC2N 5DU",
    "Post to country": "United Kingdom",
    "Item title": "Print: harbour dusk",
    Quantity: "1",
  }),
  row({
    "Sales record number": "3001",
    "Order number": "ORD-3001",
    "Buyer username": "morgan_ellis",
    "Post to name": "Morgan Ellis",
    "Post to phone": "0117 496 0234",
    "Post to address 1": "19 Queen Square",
    "Post to address 2": "Flat 2",
    "Post to city": "Bristol",
    "Post to county": "Bristol",
    "Post to postcode": "BS1 4NH",
    "Post to country": "United Kingdom",
    "Item title": "Wool scarf",
    Quantity: "1",
  }),
  row({
    "Sales record number": "3002",
    "Order number": "ORD-3002",
    "Buyer username": "morgan_ellis",
    "Post to name": "Morgan Ellis",
    "Post to phone": "0117 496 0234",
    "Post to address 1": "19 Queen Square",
    "Post to address 2": "COM24",
    "Post to city": "Bristol",
    "Post to county": "Bristol",
    "Post to postcode": "BS1 4NH",
    "Post to country": "United Kingdom",
    "Item title": "Wool gloves",
    Quantity: "1",
  }),
  row({
    "Sales record number": "4001",
    "Order number": "ORD-4001",
    "Buyer username": "chris_adeyemi",
    "Post to name": "Chris Adeyemi",
    "Post to phone": "0131 496 0199",
    "Post to address 1": "5 Calton Hill",
    "Post to address 2": "",
    "Post to city": "Edinburgh",
    "Post to county": "Midlothian",
    "Post to postcode": "EH1 3BJ",
    "Post to country": "United Kingdom",
    "Item title": "Tea tin",
    Quantity: "1",
  }),
  row({
    "Sales record number": "4002",
    "Order number": "ORD-4002",
    "Buyer username": "chris_adeyemi",
    "Post to name": "Chris Adeyemi",
    "Post to phone": "0131 496 0199",
    "Post to address 1": "5 Calton Hill",
    "Post to address 2": "",
    "Post to city": "Edinburgh",
    "Post to county": "Midlothian",
    "Post to postcode": "EH1 3BJ",
    "Post to country": "United Kingdom",
    "Item title": "Honey jar",
    Quantity: "1",
  }),
  row({
    "Sales record number": "4003",
    "Order number": "ORD-4003",
    "Buyer username": "chris_adeyemi",
    "Post to name": "Chris Adeyemi",
    "Post to phone": "0131 496 0199",
    "Post to address 1": "5 Calton Hill",
    "Post to address 2": "",
    "Post to city": "Edinburgh",
    "Post to county": "Midlothian",
    "Post to postcode": "EH1 3BJ",
    "Post to country": "United Kingdom",
    "Item title": "Shortbread tin",
    Quantity: "1",
  }),
  row({
    "Sales record number": "5001",
    "Order number": "ORD-5001",
    "Buyer username": "samira_noor",
    "Post to name": "Samira Noor",
    "Post to phone": "0121 496 0777",
    "Post to address 1": "30 Corporation Street",
    "Post to address 2": "",
    "Post to city": "Birmingham",
    "Post to county": "West Midlands",
    "Post to postcode": "B4 6TB",
    "Post to country": "United Kingdom",
    "Item title": "Tote bag",
    Quantity: "1",
  }),
  row({
    "Sales record number": "5002",
    "Order number": "ORD-5002",
    "Buyer username": "samira_noor",
    "Post to name": "Samira Noor",
    "Post to phone": "0121 496 0777",
    "Post to address 1": "30 Corporation Street",
    "Post to address 2": "W/N",
    "Post to city": "Birmingham",
    "Post to county": "West Midlands",
    "Post to postcode": "B4 6TB",
    "Post to country": "United Kingdom",
    "Item title": "Canvas pouch",
    Quantity: "1",
  }),
  row({
    "Sales record number": "6001",
    "Order number": "ORD-6001",
    "Buyer username": "incomplete_a",
    "Post to name": "No Phone Listed",
    "Post to phone": "",
    "Post to address 1": "1 Missing Fields Lane",
    "Post to address 2": "",
    "Post to city": "Leeds",
    "Post to county": "West Yorkshire",
    "Post to postcode": "LS1 1BA",
    "Post to country": "United Kingdom",
    "Item title": "Postcard pack",
    Quantity: "1",
  }),
  row({
    "Sales record number": "6002",
    "Order number": "ORD-6002",
    "Buyer username": "incomplete_b",
    "Post to name": "No Phone Listed",
    "Post to phone": "",
    "Post to address 1": "1 Missing Fields Lane",
    "Post to address 2": "",
    "Post to city": "Leeds",
    "Post to county": "West Yorkshire",
    "Post to postcode": "LS1 1BA",
    "Post to country": "United Kingdom",
    "Item title": "Stamp set",
    Quantity: "1",
  }),
  row({
    "Sales record number": "7001",
    "Order number": "ORD-7001",
    "Buyer username": "name_a",
    "Post to name": "Jordan Blake",
    "Post to phone": "0191 496 0123",
    "Post to address 1": "9 Grey Street",
    "Post to address 2": "",
    "Post to city": "Newcastle",
    "Post to county": "Tyne and Wear",
    "Post to postcode": "NE1 6AE",
    "Post to country": "United Kingdom",
    "Item title": "Cap",
    Quantity: "1",
  }),
  row({
    "Sales record number": "7002",
    "Order number": "ORD-7002",
    "Buyer username": "name_b",
    "Post to name": "Alex Blake",
    "Post to phone": "0191 496 0123",
    "Post to address 1": "9 Grey Street",
    "Post to address 2": "",
    "Post to city": "Newcastle",
    "Post to county": "Tyne and Wear",
    "Post to postcode": "NE1 6AE",
    "Post to country": "United Kingdom",
    "Item title": "Beanie",
    Quantity: "1",
  }),
  row({
    "Sales record number": "8001",
    "Order number": "ORD-8001",
    "Buyer username": "casey_rowe",
    "Post to name": "  Casey  Rowe ",
    "Post to phone": "(07700) 900-888",
    "Post to address 1": "2  Mill   Lane",
    "Post to address 2": "Unit 4",
    "Post to city": "Bath",
    "Post to county": "Somerset",
    "Post to postcode": "ba1 1ne",
    "Post to country": "uk",
    "Item title": "Soap bar",
    Quantity: "1",
  }),
  row({
    "Sales record number": "8002",
    "Order number": "ORD-8002",
    "Buyer username": "casey_rowe",
    "Post to name": "casey rowe",
    "Post to phone": "07700 900888",
    "Post to address 1": "2 Mill Lane",
    "Post to address 2": "Unit 4",
    "Post to city": "BATH",
    "Post to county": "somerset",
    "Post to postcode": "BA1 1NE",
    "Post to country": "United Kingdom",
    "Item title": "Lip balm",
    Quantity: "1",
  }),
];

export const SAMPLE_CSV = buildCsvFromRecords(
  [...SAMPLE_HEADERS],
  SAMPLE_ROWS,
);

export const SAMPLE_FILE_NAME = "sample-ebay-orders.csv";
